### PR TITLE
Docs for enabling POST requests

### PR DESCRIPTION
**Pull request by h4shk4t**

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
@juntao Please take a look. Thanks.

**Review by juntao — COMMENTED** [review]
Can you put these into a note? I would like to keep the flow of the text simple and straightforward. Thanks.

**Comment by h4shk4t** [comment]
Done! Could you please check?

**Pull request merged**
