### PR TITLE
Add webhook to discord example

### PR DESCRIPTION
**Pull request by alabulei1**

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
@juntao @DarumaDocker Please review this PR.

**Review by juntao — COMMENTED** [review]
Why do we call it webhook? I think the purpose here is to demonstrate slash commands?

**Comment by alabulei1** [comment]
> Why do we call it webhook? I think the purpose here is to demonstrate slash commands?

The main logic is that it calls a weather API to inquiry weather.

**Pull request closed without merging**
