### PR TITLE
init: intial commit for new docs

### PR DESCRIPTION
**Pull request by kokamkarsahil**
### PR changes

This PR replaces old docs with new fresh look!

It does the following changes:

- Adds default configs for editors and other docs files
- Added Chinese language [Translation needed]
- Auto generated OG image
- Tutorial components

### Deployment

No changes needed for it! It can be deployed on GitHub pages without any changes

### Docs structure

- `src/content/docs`: Main Docs with Chinese language
- `src/i18n`: Translation files
- `src/i18n/[lang]/nav.ts`: Navgiation menu

It use MDX which is same as Markdown but with extra features!

### Breaking Changes

This PR can break old links but this can be solved using redirects if needed!

### Demo

https://plankton-app-synmz.ondigitalocean.app

### Performance score:

image

On Both Mobile and Desktop: https://pagespeed.web.dev/analysis/https-plankton-app-synmz-ondigitalocean-app-en-getting-started/3lldvmgzwn

---

Thanks! Let me know if there are any questions regarding it!

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by kokamkarsahil** [comment]
Also I didn't wanted to push this to the main as it does a lot of changes. Let me know the branch needs to be change!

**Review by alabulei1 — APPROVED** [review]

**Comment by alabulei1** [comment]
@kokamkarsahil  Can you fix the conflicts?

**Comment by kokamkarsahil** [comment]
@alabulei1 done! I have to rebase each time for a new commit as it's a main branch

**Comment by kokamkarsahil** [comment]
image

The doc is built successfully, but the error is due to a permission issue, as it's not pushed into the branch yet. As mine is an external repo and pages won't allow it to run it!

**Comment by kokamkarsahil** [comment]
The GitHub page deploy was successfully: https://github.com/flows-network/docs/tree/gh-pages

But the AWS code-build failed if it was due to docs let me know!

image

**Pull request merged**
